heat_template_version: 2016-04-08

parameters:
  index:
    type: string
    default: 0
  ssh_key:
    description: SSH public key used to access runners
    type: string
    default: test
  image:
    description: Image used to create instances
    type: string
    default: cirros-0.4.0-x86_64-disk.img
  network:
    description: Network
    type: string
    default: test
  flavor:
    description: Flavor
    type: string
    default: m1.micro
  ext_net:
    description: Flavor
    type: string
    default: ext-net
  network:
    description: Private network
    type: string
    default: test
  network_subnet:
    description: Private subnet
    type: string
    default: test-subnet
  security_group:
    description: Security group
    type: string
    default: default

resources:

  instance_port:
    type: OS::Neutron::Port
    properties:
      network: { get_param: network }
      fixed_ips:
        - subnet: { get_param: network_subnet }
      security_groups: [{ get_param: security_group }]

  delay:
    type: OS::Heat::Delay
    depends_on: instance_port
    properties:
      actions: ["CREATE"]
      jitter_multiplier: 1.0
      max_jitter: 0
      min_wait: 10

  instance:
    type: OS::Nova::Server
    depends_on: delay
    properties:
      name: 
        list_join: ["-", [ "testrg",  {get_param: index} ] ]
      image: { get_param: image }
      flavor: { get_param: flavor }
      networks: [ "network": { get_param: network } ]
      key_name: { get_param: ssh_key }

  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: ext_net }
      port_id: { get_resource: instance_port }
      value_specs: { floating_ip_address:  192.168.122.210 }
